# Generated by Django 5.2.7 on 2026-04-29 23:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='曲名')),
                ('composer', models.CharField(blank=True, max_length=255, null=True, verbose_name='作曲者')),
                ('arranger', models.CharField(blank=True, max_length=255, null=True, verbose_name='編曲者')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('is_show', models.BooleanField(default=True, verbose_name='表示フラグ')),
            ],
            options={
                'verbose_name': '演奏曲',
                'verbose_name_plural': '演奏曲',
                'db_table': 'tenant_music',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='セクション')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument', verbose_name='パート')),
            ],
            options={
                'verbose_name': '編成',
                'verbose_name_plural': '編成',
                'db_table': 'tenant_formation',
            },
        ),
    ]
