# Generated by Django 5.2.7 on 2026-04-29 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='楽団'),
        ),
        migrations.AddField(
            model_name='formation',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='メンバー'),
        ),
        migrations.AddField(
            model_name='music',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='楽団'),
        ),
        migrations.AddField(
            model_name='formation',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='曲名'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('music', 'instrument', 'section'), name='unique_music_instrument_section'),
        ),
    ]
