# Generated by Django 5.2.7 on 2026-04-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='note',
            field=models.TextField(blank=True, max_length=20000, verbose_name='備考'),
        ),
    ]
