[uwsgi]
env = OTONOSU_SETTINGS=/root/.otonosu
chdir = /usr/local/dialog_pf/otonosu/orchestra_rls/orchestra_rls
# module = module=orchestra.wsgi:application
mount = /otonosu=otonosu/wsgi.py
manage-script-name = true
virtualenv = /usr/local/pyenv/versions/3.13.7/envs/otonosu-venv
master = true
chmod-socket = 666
socket = /var/run/uwsgi/otonosu.sock
pidfile = /var/run/uwsgi/otonosu.pid
logto = /var/log/uwsgi/otonosu.log
processes = 5