# Generated by Django 5.2.7 on 2026-04-29 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, '未回答'), (1, '出席'), (2, '遅刻'), (3, '早退'), (4, '欠席'), (5, '未定'), (6, '休団中')], default=0, verbose_name='出欠')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='事由')),
                ('check_in', models.BooleanField(default=False, verbose_name='チェックイン')),
            ],
            options={
                'verbose_name': '出欠',
                'verbose_name_plural': '出欠',
                'db_table': 'tenant_attendance',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('start', models.TimeField(verbose_name='開始時刻')),
                ('end', models.TimeField(verbose_name='終了時刻')),
                ('title', models.CharField(max_length=255, verbose_name='活動名')),
                ('place', models.CharField(blank=True, null=True, verbose_name='場所')),
                ('place_map_url', models.URLField(blank=True, null=True, verbose_name='場所の地図URL')),
                ('note', models.TextField(blank=True, verbose_name='活動内容')),
            ],
            options={
                'verbose_name': '活動予定',
                'verbose_name_plural': '活動予定',
                'db_table': 'tenant_schedule',
            },
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_id', models.UUIDField(verbose_name='スケジュールID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start', models.TimeField(verbose_name='開始時刻')),
                ('end', models.TimeField(verbose_name='終了時刻')),
                ('title', models.CharField(max_length=255, verbose_name='活動名')),
                ('place', models.CharField(blank=True, null=True, verbose_name='場所')),
                ('note', models.TextField(blank=True, verbose_name='活動内容')),
                ('music', models.TextField(blank=True, null=True, verbose_name='演奏曲')),
                ('attendance', models.JSONField(blank=True, null=True, verbose_name='出欠情報')),
            ],
            options={
                'verbose_name': '活動履歴',
                'verbose_name_plural': '活動履歴',
                'db_table': 'tenant_schedule_log',
            },
        ),
    ]
