# Generated by Django 5.2.7 on 2026-04-29 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_initial'),
        ('schedule', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='楽団'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='music',
            field=models.ManyToManyField(blank=True, null=True, to='music.music', verbose_name='演奏曲'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='楽団'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='schedule.schedule', verbose_name='活動'),
        ),
        migrations.AddField(
            model_name='schedulelog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='楽団'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('schedule', 'user'), name='unique_attendance'),
        ),
    ]
