# Generated by Django 5.2.7 on 2026-05-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, max_length=20000, verbose_name='活動内容'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='場所'),
        ),
    ]
