# Generated by Django 5.2.7 on 2026-04-29 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='楽器名')),
                ('initial', models.CharField(max_length=255, null=True, verbose_name='イニシャル')),
                ('jp_name', models.CharField(max_length=255, null=True, verbose_name='日本語名')),
            ],
            options={
                'verbose_name': 'Tenant Instrument',
                'verbose_name_plural': 'Tenant Instrument',
                'db_table': 'tenant_instrument',
            },
        ),
        migrations.CreateModel(
            name='InstrumentPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='パート名')),
            ],
            options={
                'verbose_name': 'パート',
                'verbose_name_plural': 'パート',
                'db_table': 'tenant_instrument_part',
            },
        ),
    ]
