# Generated by Django 5.2.7 on 2026-04-29 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrument', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='テナント'),
        ),
        migrations.AddField(
            model_name='instrumentpart',
            name='instrument',
            field=models.ManyToManyField(to='instrument.instrument', verbose_name='楽器'),
        ),
        migrations.AddField(
            model_name='instrumentpart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='instrumentpart',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='テナント'),
        ),
    ]
