# Generated by Django 5.2.7 on 2026-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
    ]
