# Generated by Django 5.2.7 on 2026-04-29 23:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import user.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='custom_permission', serialize=False, to='auth.permission')),
                ('display_name', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'カスタムパーミッション',
                'verbose_name_plural': 'カスタムパーミッション',
                'db_table': 'custom_permissions',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(max_length=255, unique=True, verbose_name='団体コード')),
                ('name', models.CharField(max_length=255, verbose_name='団体名')),
            ],
            options={
                'verbose_name': 'テナント',
                'verbose_name_plural': 'テナント',
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('member', 'メンバー'), ('guest', 'ゲスト')], default='member', max_length=10, verbose_name='ロール')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ニックネーム')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrument.instrument', verbose_name='担当楽器')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tenant')),
            ],
            options={
                'verbose_name': '団員',
                'verbose_name_plural': '団員',
                'db_table': 'tenant_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permissions', models.ManyToManyField(related_name='presets', to='user.custompermission')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tenant')),
            ],
            options={
                'verbose_name': 'パーミッションプリセット',
                'verbose_name_plural': 'パーミッションプリセット',
                'db_table': 'permission_presets',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='理由')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tenant', verbose_name='テナント')),
            ],
            options={
                'verbose_name': '休団申請',
                'verbose_name_plural': '休団申請',
                'db_table': 'leave_applications',
            },
        ),
        migrations.CreateModel(
            name='UserActivateTokens',
            fields=[
                ('token_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_token', models.UUIDField(unique=True)),
                ('expiration_date', models.DateTimeField(default=user.models.get_after_30_days)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset_count_for_today', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザーアクティベートトークン',
                'verbose_name_plural': 'ユーザーアクティベートトークン',
                'db_table': 'user_activate_tokens',
            },
        ),
    ]
