# Generated by Django 5.2.7 on 2026-05-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='理由'),
        ),
    ]
